########################################################
# creates postgres sql database image and pgadmin4 image
# login db: postgres:postgres hostname: postgres
# login pgadmin: admin@developer-blog.net:admin port 5555
########################################################
version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
# if you need to connect from outside, comment this in:
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./scheme.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
volumes:
  postgres-data: